name: CI/CD Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run migrations inside container
        run: |
          docker run --rm \
            --network container:sqlserver \ # or use the same docker network name
            -v ${{ github.workspace }}:/src \
            -w /src/InteractiveFloor \
            mcr.microsoft.com/dotnet/sdk:8.0 \
            bash -c "dotnet tool restore && dotnet ef database update"

      - name: Run app containers
        run: docker compose up --build -d

