name: CI/CD Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  apply-migration:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: "8.0.x"
      PROJECT_DIR: TaskManagement
      DB_CONNECTION: "${{ secrets.DB_CONNECTION }}"
      CONNECTION_KEY: "ConnectionStrings__DefaultConnection"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Migration DB
        run: |
            cd ${PROJECT_DIR}
            dotnet tool install --global dotnet-ef
            dotnet tool restore
            export "${CONNECTION_KEY}=$DB_CONNECTION"
            dotnet-ef database update

  docker-compose:
    runs-on: self-hosted
    environment: docker
    env:
      DB_CONNECTION: "${{ secrets.DB_CONNECTION }}"
      JWT_KEY: "${{ secrets.JWT_KEY }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Run app containers
        run: |
          export DB_CONNECTION="$DB_CONNECTION"
          export JWT_KEY="$JWT_KEY"
          docker compose up --build -d
